#! /bin/bash

FILES="junit.rst git.rst git.rst script.rst yaml.rst conventions.rst bestpractices.rst"
touch complete.rst
rm complete.rst
pandoc -s -t rst --toc manuel.rst junit.rst git.rst script.rst yaml.rst conventions.rst bestpractices.rst -o complete.rst

