#!/usr/bin/python2

# A modifier : 
# La liste expectedFiles, mettre les fichiers attendus dans l'archive zip.

from os import listdir, system
import zipfile
import inginiousUtils

# Verify the file content
system('getinput "q1" > basicSubmission.zip')

#totalPoints = 0
#maxPoints = 5

output = ".. role:: bash(code)\n\t:language: bash\n\n"

title1 = "Testing content of archive"
output += inginiousUtils.get_rst_title(title1) + "\n\n"

expectedFiles = ['Classement.java', 'ClassementTemps.java', 'Coureur.java', 'DList.java', 'DListTest.java', 'Main.java', 'Resultat.java', 'Temps.java', 'README.TXT']

unzipOutput = inginiousUtils.extract_zip_content('basicSubmission.zip', expectedFiles)

if (unzipOutput):
    output += unzipOutput
    output += "\n**Archive Content: 0/1**"
    system('archive -a build.manifest')
    system('feedback --result failed --feedback "' + output + '"')
    exit(0)
else:
    output += "Your archive has the correct content.\n"
    output += "\n**Archive content: 1/1**"
    system('sh run.sh')
