#!/usr/bin/python2

# A modifier : 
# La liste expectedFiles, mettre les fichiers attendus dans l'archive zip.

from os import listdir, system
import zipfile
import subprocess
import inginiousUtils


system('export LC_ALL=en_US.UTF-8')
system('export LANG=en_US.UTF-8')
system('export LANGUAGE=en_US.UTF-8')

# Verify the file content
system('getinput "q1" > basicSubmission.zip')

#totalPoints = 0
#maxPoints = 5

output = ".. role:: bash(code)\n\t:language: bash\n\n"

title1 = "Testing content of archive"
output += inginiousUtils.get_rst_title(title1) + "\n\n"

expectedFiles = ['Equation.java', 'EquationSimple.java', 'TextIO.java', 'README.TXT']

unzipOutput = inginiousUtils.extract_zip_content('basicSubmission.zip', expectedFiles)

if (unzipOutput):
    output += unzipOutput
    output += "\n**Archive Content: 0/1**"
    system('archive -a build.manifest')
    system('feedback --result failed --feedback "' + output + '"')
    exit(0)
else:
    system('sh custom.sh')
    outjavac = ""
    try:
    	subprocess.check_output("javac student/*.java", stderr = subprocess.STDOUT, shell = True)
    	output += "Your archive has the correct content.\n"
    	output += "\n**Archive content: 1/1**"
    	system('feedback --result success --feedback "' + output + '"')
    except subprocess.CalledProcessError, e:
        output += "There are some compilation errors with your program :\n::\n\n"
        system("echo \""+e.output+"\" > outjavac.log")
    	output += subprocess.check_output("sed -e \'s/^/\\t/\' < outjavac.log", shell = True)
    	system('feedback --result failed --feedback "' + output + '"')
     
    
    exit(0)
